name: sign_in
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  component_library:
    path: ../../component_library
  flutter_bloc: ^7.1.0
  flutter:
    sdk: flutter
  user_repository:
    path: ../../user_repository
  form_fields:
    path: ../../form_fields
  domain_models:
    path: ../../domain_models

dev_dependencies:
  mocktail: 0.1.4
  test: ^1.17.9
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true