name: quote_details
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  component_library:
    path: ../../component_library
  equatable: ^2.0.3
  flutter_bloc: ^7.1.0
  share_plus: ^2.1.4
  flutter:
    sdk: flutter
  quote_repository:
    path: ../../quote_repository
  domain_models:
    path: ../../domain_models

dev_dependencies:
  mocktail: 0.1.4
  test: ^1.17.9
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true